#!/bin/sh
#
# Parameters: <scandir>
#
# <scandir> contains several files which have been scanned in a batch mode.
# The files follow the pattern 'scan.DDD.tif"
#

SCANDIR="$1"
BINDIR=/opt/autoscan

BATCHSIZE="$(ls $SCANDIR/* | wc -l)"
i=1
for SCANFILE in $SCANDIR/*
do
	$BINDIR/autoscan-process "$SCANFILE" "$BATCHSIZE" "$i"
	i=$(expr $i + 1)
done

