#!/bin/sh

# set -x

SPOOLDIR=/var/spool/autoscan
ARCHIVEDIR=/archive/autoscan
SELF=$(basename "$0")

cd "$SPOOLDIR" || 
{ 
    logger "Could not enter spool directory $SPOOL"
    exit 1 
}

num_sent=$(ls */*.sent 2>/dev/null | wc -l)
if [ "$num_sent" = "0" ]
then
    echo "No files with extension '.sent' found for processing!"
    exit 1
fi

find . -type f -name '*.sent' 2>/dev/null |
while read SENT
do
    DIRNAME=$(dirname "$SENT")
    BASEDIR=$(basename "$DIRNAME")
    BASEFILE=$(basename "$SENT" .pdf.sent)

    echo "Processing file '$BASEFILE'..."
    case "$SELF" in
	autoscan-archive)

	    # Keep the original .PDF for archival purposes.
	    if [ -r "$BASEDIR/$BASEFILE".pdf ]
	    then 
		mv "$BASEDIR/$BASEFILE".pdf "$ARCHIVEDIR/$BASEDIR.$BASEFILE.pdf"
		if [ $? != 0 ]
		then 
		    exit 1
		fi
	    fi

	    # Keep the original .TIF for local OCR.
	    if [ -r "$BASEDIR/$BASEFILE".tif ]
	    then 
		mv "$BASEDIR/$BASEFILE".tif "$ARCHIVEDIR/$BASEDIR.$BASEFILE.tif"
		if [ $? != 0 ]
		then 
		    exit 1
		fi
	    fi

	    rm -f "$BASEDIR/$BASEFILE"*
	    rmdir "$DIRNAME"
	    ;;

	autoscan-clear)
	    rm -f "$BASEDIR/$BASEFILE"*
	    rmdir "$DIRNAME"
	    ;;
	*)
    esac
done